export const  jsonSave = { 
    "PRODUCCION":{ 
       "CABECERA":{ 
          "nit":String,
          "nombre_acreedor":String,
          "direccion":String,
          "correo_electronico":String,
          "doc_compra":String,
          "orden_fabricacion":String,
          "material":String,
          "texto_material":String,
          "tulas":String,
          "cajas":String,
          "bolsas":String,
          "consecutivo_ord_procesa":null,
          "transportador":null,
          "hora_recogida":null,
          "fecha_recogida":null,
          "campana_orden":String,
          "prioridad":String,
          "fecha_entrega":String,
          "categoria_stock":String,
          "usuario":String,
          "transporte_propio":false,
          "taller":null,
          "observacion":null,
          "Fecha_creacion":null,
          "Hora_creacion":null,
          "DETALLE":[ 
             { 
                "valor_matriz":String,
                "plu":String,
                "cantidad_inicial":String,
                "cantidad_pendiente":String,
                "cantidad_entregar":String,
                "cantidad_confirmada":String,
                "cantidad_maxima":null,
                "posicion_pedido":String,
                "Consecutivoscita":null
             },
             { 
                "valor_matriz":String,
                "plu":String,
                "cantidad_inicial":String,
                "cantidad_pendiente":String,
                "cantidad_entregar":String,
                "cantidad_confirmada":String,
                "cantidad_maxima":null,
                "posicion_pedido":String,
                "Consecutivoscita":null
             },
             { 
                "valor_matriz":String,
                "plu":String,
                "cantidad_inicial":String,
                "cantidad_pendiente":String,
                "cantidad_entregar":String,
                "cantidad_confirmada":String,
                "cantidad_maxima":null,
                "posicion_pedido":String,
                "Consecutivoscita":null
             },
             { 
                "valor_matriz":String,
                "plu":String,
                "cantidad_inicial":String,
                "cantidad_pendiente":String,
                "cantidad_entregar":String,
                "cantidad_confirmada":String,
                "cantidad_maxima":null,
                "posicion_pedido":String,
                "Consecutivoscita":null
             }
          ]
       }
    }
 } 
 